### ISSUE TITLE
Need some help if able!

### ISSUE THREAD

**Issue by XenXenOfficial** [tomer8007/kik-bot-api-unofficial#80] opened 2018-10-08 19:01 UTC
Hello! I'm a bit confused on the documentation of the API, I'm trying to figure out how to send a message to a specific group chat, but I can't seem to find anything related to that, even by manually viewing it with the ```help ``` function on python. I have seen some mentions of ```.send_message ``` but it seems to not be a method and it doesn't show in the ```help```. Any help? Am I using an outdated version of the API?

**Comment by tomer8007** [comment] 2018-10-08 19:40
I think you're using the `master` branch, which is old.

The `new` branch has a `send_chat_message` method, which requires a JID of the person or the group to which you want to send the message to. You can read the help for that method (it exists).

**Comment by XenXenOfficial** [comment] 2018-10-08 20:10
Hey, Thanks! That fixed my issue 👍 Have a great day

**Comment by XenXenOfficial** [comment] 2018-10-08 20:16
Oh hey, another question. Is it possible to have the bot send an image via a URL?

Edit:

I see you haven't implemented the option to send images. Would you be able to include that eventually? Is it too complex of an option?

**Comment by tomer8007** [comment] 2018-10-09 09:28
Not really too complex, just a matter of having enough time and will to sniff kik's traffic again, understand the format and implement that into the API. 

I'm not sure if it's there, but you could look at the wiki page where we share the different formats. Maybe there's already an example of sending images?

**Comment by XenXenOfficial** [comment] 2018-10-09 16:13
Hey! I tried doing what you said a shot and it doesn't give me an error message, in the "kik-log.txt" file, it says "[2018-10-09 11:51:59,783] DEBUG  (thread Kik Connection): [!] Main loop ended.". I'm not exactly sure what it means, but here's my code and the data structure of the image: https://github.com/XenXenOfficial/Playing-With-Python/blob/master/Kik-Unofficial-Api:%20Image%20Issue

If you have any suggestions that would be great :)

**Comment by XenXenOfficial** [comment] 2018-10-10 03:25
I believe my issue is in my `<preview></preview>` for the image, the  `<preview></preview>` gives me _tons_ of garbage text that's apparently the image, and I'm unsure of what it means :/

Edit:
I'm pretty sure its an RSA generated key for the image preview and I got no idea where to go to from here hahaha.

**Comment by tomer8007** [comment] 2018-10-11 11:07
Thtat's quite interesting. If you manage to get it working it's worth doing a pull request so that it'll get added to the API.

But wait, what makes you think that the `<preview>` tag is an RSA generated key? Also, what happens if you try to send the image without a `<preview>` field? 

EDIT: What's the response that kik servers return? I don't see it in your file.

**Comment by XenXenOfficial** [comment] 2018-10-11 12:40
(I'm extremely noob with keys, I've never worked with them so go easy me if I'm incorrect) I believe it's a RSA generated key because in the preview tag (of when an image is being sent to me might I add, I figure I need to simulate it to be able to send an image) the key is strikingly similar to the one provided in the client legacy py file under `private_key_pem`. I'll send an Pastebin file of the preview. 

No preview gives the same outcome, `(Program exited with code: 0)`

And I'm not entirely sure how to get a response from the server haha If you could help me on that it would be a good way of debugging haha

**Comment by tomer8007** [comment] 2018-10-11 12:44
the exact server response should be logged in the DEBUG log.

**Comment by XenXenOfficial** [comment] 2018-10-11 12:45
Oh lmao give me a sec I'll go check it out

Edit:
https://pastebin.com/6BhXQRUq

Heres what happens after I send my trigger word for the bot

**Comment by XenXenOfficial** [comment] 2018-10-11 12:55
It doesn't seem to respond, it just dies on me haha

**Comment by XenXenOfficial** [comment] 2018-10-12 03:51
I've edited the code to be more similar to an image being sent from a user, it doesn't crash anymore, but it doesn't send the image either. Any suggestions?

Heres the new updated code:
https://github.com/XenXenOfficial/Playing-With-Python/blob/master/Kik-Unofficial-Api:%20Image%20Issue

**Comment by tomer8007** [comment] 2018-10-12 11:03
I think that usually when the connection ends unexpectdely like that it's because kik doesn't like some stuff you sent. But now you're saying they don't return anything at all? That doens't make a lot of sense. They should at least return an `ack`.

**Comment by XenXenOfficial** [comment] 2018-10-12 16:43
Yea what was happening is that I was trying to mimic an image being sent by using the `chat_messsge.__dict__.items()` and the program was crashing when I did lol, so what I'm doing now is that I made a normal Kik bot and sent an image to it then checked the post request in `ngrok` which is a free server program Kik suggested. So I remade the function to mimic that, which apparently works but it doesn't reply

**Comment by XenXenOfficial** [comment] 2018-10-12 20:02
Hey! I edited it around and I'm getting a reply, but its an error. Heres the pastebin: https://pastebin.com/5Vrg4CRw

Edit: Figured out my error and I'm still getting an `ack` reply, but it doesn't seem to do anything. https://pastebin.com/fBLeAfzW

**Comment by XenXenOfficial** [comment] 2018-10-13 20:50
I made a little bit of progress, Kik's servers will automatically reply to my bot when it wasn't in the group chat for a 24 hour period. So it's sending the image, and Kik is recognizing it's an image, but it won't send it or preview it lol.

**Comment by XenXenOfficial** [comment] 2018-10-14 06:12
I think it's not popping up cause the received data has `push=false` do you know how i could fix this?? Please reply.

**Comment by tomer8007** [comment] 2018-10-14 11:24
I need some time to look at it, but it sounds like you're progressing nicely so far.

Right now I'm not sure what that push parameter says. I need to check that

**Comment by XenXenOfficial** [comment] 2018-10-14 17:43
Would you know how i could grab the image data before it gets sent to Kiks servers? I'm not entirely sure how i could do that, and i feel like if i can see how an image being sent, i can mimic it in python lol

**Comment by d3vvil** [comment] 2018-10-14 18:54
use a packet sniffer like charles. the image data is sent via http

**Comment by XenXenOfficial** [comment] 2018-10-14 23:03
> 
> 
> use a packet sniffer like charles. the image data is sent via http

Hey! I tried doing what you suggested, but it didn't pick anything up. I suspect im doing it wrong, but i tried following a tut lol installing the certificate and setting my PC as the proxy. Any suggestions?

**Comment by d3vvil** [comment] 2018-10-15 03:52
i logged the image upload using a packet sniffer for android which isn't available on playstore anymore and uploaded the log to a file hosting site: http://s000.tinyupload.com/index.php?file_id=08031365646837193195

**Comment by XenXenOfficial** [comment] 2018-10-15 04:08
> 
> 
> i logged the image upload using a packet sniffer for android which isn't available on playstore anymore and uploaded the log to a file hosting site: http://s000.tinyupload.com/index.php?file_id=08031365646837193195

This is, for the most part, perfect. I can make out some stuff that i can definitely change in my code, but a lot of the data seems to be messed with. Could you try uploading it to a different site? I've had issues with tinyupload in the past haha

**Comment by d3vvil** [comment] 2018-10-15 06:42
https://ufile.io/42jbu

**Comment by XenXenOfficial** [comment] 2018-10-16 13:30
Yea, I can see some data but the rest seems to be all jumbled up. There is some readable data there but I don't believe it's all of it

**Comment by d3vvil** [comment] 2018-10-16 13:31
the text at the very top is the http request, the "data" is the actual image itself being transferred. following the image data is a sort of http "ok" response

**Comment by XenXenOfficial** [comment] 2018-10-16 13:35
Ahhh alright.

**Comment by XenXenOfficial** [comment] 2018-10-16 13:37
I'm currently at class right now, I'll take another swing at it when I get some time after class

**Comment by XenXenOfficial** [comment] 2018-10-16 14:59
@d3vvil Hey, would it be possible for you to send the same thing but when you send a message? I can't seem to figure it out even with the data you've given me, so I want to compare the text http to the xml the developer has here

**Comment by d3vvil** [comment] 2018-10-16 15:37
you can't read the messages with a packet sniffer. you can, but all the data that's transfered over the xmpp protocol is encrypted. both sides(incoming/outgoung) are encrypted

**Comment by XenXenOfficial** [comment] 2018-10-16 15:52
If it's all encrypted, how'd the developer go ahead and create the XML message that's exactly what he needs? :0

**Comment by XenXenOfficial** [comment] 2018-10-27 23:00
Hey, I changed a good portion of the code around and added some stuff to try and get it working, but still, nothing shows up. Here's the code: https://pastebin.com/crxJY8Kj the kik converts the image to jpeg and compresses it, so thats why included the other bit of code there

**Comment by XenXenOfficial** [comment] 2018-11-09 21:01
Hey! I've talked with some people and they said I needed to have the image hosted on a webserver. So I got one up and running and I'm trying to get SFTP running on it, but I don't know what's wrong, it gives me a permission denied error on it and I have the SFTP user owning all of the files lol

**Comment by XenXenOfficial** [comment] 2018-11-11 12:48
Hey, I got it all working but I'm running into a 403 issue lol Not exactly sure what to do from here

**Comment by tomer8007** [comment] 2018-11-11 18:35
Can you send images? How?

**Comment by XenXenOfficial** [comment] 2018-11-12 22:38
> 
> 
> Can you send images? How?

Hey, I can't send images yet, but it's not denying my request to send an image. I don't know if i can get any debug from their server on why they wouldn't send it? Is that even a possibility?

**Comment by tomer8007** [comment] 2018-11-16 13:09
Unfortunately I don't know of any way to get detailed debug information from their servers. Usually what I do in these cases is just see how their APK is doing that and try to mimic that.

**Comment by XenXenOfficial** [comment] 2018-11-16 14:28
That's what I figured, but I think what's wrong is that I gotta upload the image to Kiks servers, grab the image URL and then send that out instead of just any random URL. I'm assuming this because whenever I get a reply back from an image, it isn't the users file location or anything like that, it's always off of their servers. So do you know if there is any reference to uploading anything in the SMALI files?

**Comment by d3vvil** [comment] 2018-11-16 16:05
from the disassembly i'd look at the files in kik.android.net.http

**Comment by XenXenOfficial** [comment] 2018-11-16 16:57
> 
> 
> from the disassembly I'd look at the files in kik.android.net.http

I don't seem to that folder when I decompile Kik. Would you be able to assist me?

**Comment by d3vvil** [comment] 2018-11-16 21:52
disassemble the dex files of the latest version of the kik app

**Comment by XenXenOfficial** [comment] 2018-11-17 07:18
A user assisted me in getting the outgoing sticker message XMPP. https://pastebin.com/ZtdadA1A 

I've cleaned it up a little, i had to add the last two lines because when i received it, it didn't include the two last ending bits.

**Comment by XenXenOfficial** [comment] 2018-11-17 07:19
Oops. Seemed to have forgotten to close `<png-preview>`

**Comment by tomer8007** [comment] 2018-11-17 12:50
@XenXenOfficial Is it working?

**Comment by XenXenOfficial** [comment] 2018-11-17 14:00
@tomer8007 no :/ I'm not too sure why.

**Comment by dexterdj** [comment] 2018-12-04 15:09
Hi,
Have you any got update about this development ?

Thx

**Comment by XenXenOfficial** [comment] 2018-12-04 20:02
I'm pretty sure I'd need to make the bot upload the image to kiks servers and then grab the link. The code is exactly the way a image being sent would look like, but it won't send the image. And since I'm not familiar with Kik SMALI files, I cannot get any development going

**Comment by dexterdj** [comment] 2018-12-04 21:15
@XenXenOfficial 

Dit you tried to sniff network traffic with SSLstrip and whireshark ? Maybe official app upload the image using other protocol on other port ?

**Comment by dexterdj** [comment] 2018-12-05 00:29
Hello,
I need help to use the tool to help analyzing the process.
(Would like to send photos too ^^)

I installed SSLsplit on a debian VM.
Port 5223 is forwarded with iptable.
CA is generated, and installed on my phone (android).
Default gateway of the phone set to VM IP.

Script launched, i intercept traffic. I have a kik logfile (port5223) but data seems to be binaries;
https://imageshack.com/i/poldIE78p

What is the next step so see clear data plz ?
Do I have to bind certificate to kik apk to ensure ssl encryption will use my crt and will be decrypted by the proxy ?

**Comment by XenXenOfficial** [comment] 2018-12-05 00:48
If you use the GitHub package to capture incoming images, you can see where the image is being uploaded. I'm sure you could use SFTP to upload the image, but I'm unsure what the SSH key would be.

**Comment by dexterdj** [comment] 2018-12-05 01:38
Just found somme little informations analyzing an old bot. (Obfusced code)

The client send the photo in HTTPS PUT to platform.kik.com/content/files/ [GUID].jpg with a new GUID as filename.
The HTTPS PUT request have headers:

UserAgent: Kik/9.5.1.4513 (Android 5.0.2) Content
x-kik-jid: self kik address
x-kik-password: encrypted ? have to analyze the obfusced code ^^
x-kik-verification: Not the same value, have to analyze too 
x-kik-app-id: com.kik.ext.camera / galery
x-kik-content-chunks: 1
x-kik-content-size: Image size
x-kik-content-md5: Image MD5
x-kik-chunk-number: 0
x-kik-chunk-md5: Image MD5 again
Content-Type: image/jpeg
x-kik-content-extension: " .jpg"


After the uploading, the GUID is used as filename is used as <content> id in the xmpp message.

<preview> and <icon> tags contains the base64 value of the bytearray representing the file.

I can share the archive of the obfusced c# code source if interested ?

**Comment by dexterdj** [comment] 2018-12-05 01:43
https://imageshack.com/a/img922/9760/92ZDLT.png

I dont know if it's a test code or a production  code, but it's a good info to imagine the process.
I used this bot in the past, but I did not use the photos sender system.

**Comment by XenXenOfficial** [comment] 2018-12-05 08:41
Where'd you get that code?

**Comment by dexterdj** [comment] 2018-12-05 09:22
It's an old bot. Used it in the past and stop worked. I dont have the newer paid version.

I decompiled it with ILSpy, the code is in .zip archive, link available 7days:
https://wetransfer.com/downloads/00629108cd2e0eb310f68b0b52db0f7420181205085752/2c6a42f837816ab6d70be81e57b2496320181205085752/fb3c62

Open ******\KikWorker.cs and go th the last function; method_8(string string_8).

It's the function to send image.

The code is obfusced. Exemple : Class9.smethod_251(byte_2).
Tu understand this, we have to "Find in all files" the differents expressions.
For exemple search for "smethod_251", and you will find a conversion function in Class9.cs object.

this.string_4 => It's the password_key (same sent in xmpp login)
value2 => It's a generated GUID in lower and without "-".


It it possible for you, to sniff the 443 port on a phone with kik apk, and detect the HTTPS PUT request when the app send photo ? (We need to confirm it use HTTP with these headers).

I continue some tests and analyses ... I still have problem analyzing SSL encrypted traffic :)

**Comment by d3vvil** [comment] 2018-12-05 12:22
i posted the complete http req for uploading an image earlier in this issue: http://s000.tinyupload.com/index.php?file_id=08031365646837193195 its a text file so just open with notepad or w.e

**Comment by XenXenOfficial** [comment] 2018-12-05 12:46
Forgot all about that file. Ill see if I can get the upload working in Python since I got the info I need now

**Comment by dexterdj** [comment] 2018-12-05 12:47
Cool !

Thanks man (previous link was broken ^^).

Do you know from where these values from ?

x-kik-chunk-md5: f751a6fb2d3514935a8ff64f13bc6b25
x-kik-sha1-original: 6AE0CEA589DE889213B5D6248C281CB507DF2783
x-kik-sha1-scaled: 3BB80F2DB611834D5CBD6099DEC6355DE650B2DC
x-kik-blockhash-scaled: 0000F00FFFFFF80030007800F800F800FC00F8007800F800FF00C000E003F003

**Comment by XenXenOfficial** [comment] 2018-12-05 13:03
Not entirely sure tbh haha maybe someone here knows

**Comment by XenXenOfficial** [comment] 2018-12-05 13:09
Actually, I think those are the hashes for the Kik application

**Comment by dexterdj** [comment] 2018-12-05 14:13
> 
> 
> So do you know if there is any reference to uploading anything in the SMALI files?

Found this in SMALI files: https://imageshack.com/a/img921/6234/zEwyAZ.png
It's http headers.

@d3vvil  do you found othed interesting things in kik apk sources ? SMALI is diffucult to read ... :s

**Comment by d3vvil** [comment] 2018-12-05 15:52
@dexterdj https://pastebin.com/raw/fPj8X6bK have a look at the method ".method final c()I". all the headers for the http req are there

**Comment by d3vvil** [comment] 2018-12-06 00:46
@dexterdj sure i guess but i don't think this is the right place to be sending messages back and forth. message me on kik: darthvader_98

**Comment by SamHoque** [comment] 2018-12-09 23:16
You don't have to upload the image to kik servers, You can push an Image XMPP with just the preview.

**Comment by SamHoque** [comment] 2018-12-09 23:18
> > So do you know if there is any reference to uploading anything in the SMALI files?
> 
> Found this in SMALI files: https://imageshack.com/a/img921/6234/zEwyAZ.png
> It's http headers.
> 
> @d3vvil do you found othed interesting things in kik apk sources ? SMALI is diffucult to read ... :s

Smali is just a mix of instruction, It's easy to understand It once you know how registers work. If you have problem with smali you can turn kik's source code to java using Jadx. https://github.com/skylot/jadx

**Comment by XenXenOfficial** [comment] 2018-12-25 16:41
> 
> 
> You don't have to upload the image to kik servers, You can push an Image XMPP with just the preview.

We both know we already tried that with no success lol, you even looked over my XMPP code and verified everything was fine.

**Comment by SamHoque** [comment] 2018-12-25 16:46
Not sure why it didn't work on the python client, but that's how I did it on Lynx 1 years back.

**Comment by XenXenOfficial** [comment] 2018-12-25 16:47
> 
> 
> Not sure why it didn't work on the python client, but that's how I did it on Lynx 1 years back.

Hmm, aren't you using a modified Kik client though?

**Comment by SamHoque** [comment] 2018-12-25 16:51
Not sure why that would matter, the XMPP is valid that's all I'm saying.

**Comment by XenXenOfficial** [comment] 2018-12-25 16:57
> 
> 
> Not sure why that would matter, the XMPP is valid that's all I'm saying.

Because when you upload the image with the Kik client, I think you're making a custom XMPP or whatever for Lynx, but you're still uploading the image the Kik's servers to host. The HTTP headers and everything would be set for you.

Unlike the python client where we have no Kik application, just pure code.

**Comment by SamHoque** [comment] 2018-12-25 16:59
Hahaha, that's not how it works. I wish tho. The image is unable to load into full preview because there isn't a URL, It's the same as any other XMPP you would send not sure why Kik would modify anything for you since I'm writing it to their outputstream directly, I have log XMPP as I have mentioned before I have never seen anything being added

**Comment by XenXenOfficial** [comment] 2018-12-25 17:00
> 
> 
> Hahaha, that's not how it works. I wish tho. The image is unable to load into full preview because there isn't a URL, It's the same as any other XMPP you would send not sure why Kik would modify anything for you since I'm writing it to their outputstream directly, I have log XMPP as I have mentioned before I have never seen anything being added

Hmm. Maybe we're missing something in the XMPP?

**Comment by SamHoque** [comment] 2018-12-25 17:03
No, I don't think that's the issue. I'm pretty sure it's something else my computer broke so I can't really debug anymore but I think I told you I figured out why it didn't work

**Comment by XenXenOfficial** [comment] 2018-12-25 17:06
> 
> 
> No, I don't think that's the issue. I'm pretty sure it's something else my computer broke so I can't really debug anymore but I think I told you I figured out why it didn't work

Rip completely forgot haha

**Comment by SamHoque** [comment] 2018-12-26 00:23
Okay, Look's like the issue is something else. I tried sending a picture/sticker from my java client but it isn't sending like we saw in the python client, but It's the exact same XMPP I send via my modded kik. So I honestly have no clue what's going on here, My guess is kik is detecting this isn't an android device sending the XMPP so lets block it

**Comment by SamHoque** [comment] 2018-12-26 00:32
@dexterdj can you send me the URL to where you got that bot? Like their official website? Couldn't find any trace of it.

**Comment by SamHoque** [comment] 2018-12-26 00:33
@XenXenOfficial @dexterdj I will attempt to write a java code that uploads images to kik servers and get back here if I am successful with it.

**Comment by SamHoque** [comment] 2018-12-26 00:35
>           Cool !
> Thanks man (previous link was broken ^^).
> Do you know from where these values from ?
> x-kik-chunk-md5: f751a6fb2d3514935a8ff64f13bc6b25
> x-kik-sha1-original: 6AE0CEA589DE889213B5D6248C281CB507DF2783
> x-kik-sha1-scaled: 3BB80F2DB611834D5CBD6099DEC6355DE650B2DC
> x-kik-blockhash-scaled: 0000F00FFFFFF80030007800F800F800FC00F8007800F800FF00C000E003F003

Those are generated code from the actual image file.

**Comment by XenXenOfficial** [comment] 2018-12-26 00:36
> 
> 
> @dexterdj can you send me the URL to where you got that bot? Like their official website? Couldn't find any trace of it.

I got the files he provided.



> 
> 
> @XenXenOfficial @dexterdj I will attempt to write a java code that uploads images to kik servers and get back here if I am successful with it.

Any progress?

**Comment by sapiosaurus** [comment] 2019-01-02 23:22
I'm working on this now as well, can anyone who has the decompiled/interpreted version expand on the process to retrieve the GUID we need to use to make the PUT request?
Do I simply randomly create a guid and hope it works, or is there a mechanism for this in advance?

**Comment by sapiosaurus** [comment] 2019-01-02 23:25
> https://imageshack.com/a/img922/9760/92ZDLT.png
> 
> I dont know if it's a test code or a production code, but it's a good info to imagine the process.
> I used this bot in the past, but I did not use the photos sender system.

In your image above, any chance you can post the code that appears before the first line in the image? I am close on the uploader, but am missing Class9 (method: smethod_160) which appears to take a username/password and auto salt... as well as the output for the GUID to send in the PUT request(output of guid2)

**Comment by tomer8007** [comment] 2019-01-04 11:12
@drmarvel  Not sure about it, but did you try [kik's GUID generation method](https://github.com/tomer8007/kik-bot-api-unofficial/blob/new/kik_unofficial/utilities/cryptographics.py#L64)?

**Closed as completed** 2020-04-26 14:33 UTC
Labels: help wanted
