### ISSUE TITLE
How to get username from JID?

### ISSUE THREAD

**Issue by KyleSforza** [tomer8007/kik-bot-api-unofficial#218] opened 2022-11-04 13:53 UTC
How do you extract username from someone's JID?

**Comment by tomer8007** [comment] 2022-11-04 19:37
Duplicate of #206.

**Comment by tomer8007** [comment] 2022-11-04 19:42
I think what you're looking for is `request_info_of_users`:
https://github.com/tomer8007/kik-bot-api-unofficial/blob/75471620fdbb93061a11c1b31366479509b25022/kik_unofficial/client.py#L237

**Closed as completed** 2023-03-20 22:17 UTC
